from pathlib import Path

from app.models.schemas import ScanResult


def generate_markdown_report(result: ScanResult, output_path: Path | None = None) -> str:
    lines: list[str] = []
    r = result
    sv = r.vulnerabilities_by_severity

    lines += [
        f"# Supply Chain Security Report — {r.project_name}",
        "",
        "## Executive Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| Project | {r.project_name} |",
        f"| Scan Date | {r.scan_date.strftime('%Y-%m-%d %H:%M UTC')} |",
        f"| Scanner Version | {r.scanner_version} |",
        f"| Dependencies Analyzed | {r.total_dependencies} |",
        f"| Vulnerabilities Found | {r.total_vulnerabilities} |",
        f"| Risk Score | **{r.risk_score.total}/100** |",
        f"| Risk Level | **{r.risk_score.level.value}** |",
        "",
        "## Vulnerabilities by Severity",
        "",
        f"| Severity | Count |",
        f"|---|---|",
        f"| Critical | {sv.get('critical', 0)} |",
        f"| High | {sv.get('high', 0)} |",
        f"| Medium | {sv.get('medium', 0)} |",
        f"| Low | {sv.get('low', 0)} |",
        "",
    ]

    if r.vulnerabilities:
        lines += [
            "## Detected Vulnerabilities",
            "",
            "| Package | Version | Severity | CVSS | Type | ID | Summary |",
            "|---|---|---|---|---|---|---|",
        ]
        _TYPE_LABELS = {
            "cve": "CVE",
            "supply_chain_attack": "Supply Chain Attack",
            "abandoned": "Abandoned",
            "typosquatting": "Typosquatting",
        }
        for v in sorted(r.vulnerabilities, key=lambda x: x.cvss, reverse=True):
            type_label = _TYPE_LABELS.get(v.vuln_type.value if hasattr(v.vuln_type, 'value') else str(v.vuln_type), str(v.vuln_type))
            lines.append(
                f"| {v.package} | {v.installed_version or 'unknown'} | "
                f"{v.severity.value.upper()} | {v.cvss} | "
                f"{type_label} | "
                f"{v.vulnerability_id} | {v.summary[:80]} |"
            )
        lines.append("")

    if r.remediations:
        lines += [
            "## Remediation Recommendations",
            "",
        ]
        for idx, rem in enumerate(
            sorted(r.remediations, key=lambda x: x.priority.value), start=1
        ):
            lines += [
                f"### {idx}. {rem.package} ({rem.ecosystem.value})",
                "",
                f"- **Risk:** {rem.risk}",
                f"- **Impact:** {rem.impact}",
                f"- **Evidence:** {rem.evidence}",
                f"- **Action:** {rem.action}",
            ]
            if rem.suggested_command:
                lines += [
                    f"- **Suggested Command:**",
                    f"  ```",
                    f"  {rem.suggested_command}",
                    f"  ```",
                ]
            lines += [f"- **Priority:** {rem.priority.value.upper()}", ""]

    lines += [
        "## SBOM (Simplified)",
        "",
        "| Package | Version | Ecosystem | Type |",
        "|---|---|---|---|",
    ]
    for comp in r.sbom.components:
        lines.append(
            f"| {comp.name} | {comp.version or '-'} | {comp.ecosystem.value} | {comp.dependency_type.value} |"
        )

    lines += [
        "",
        "## Analysis Limits",
        "",
    ]
    for limit in r.analysis_limits:
        lines.append(f"- {limit}")

    lines += [
        "",
        "---",
        "*Generated by Supply Chain Security Scanner*",
        "",
    ]

    content = "\n".join(lines)
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")
    return content
